security:
    encoders:
        Gosyl\CommonBundle\Entity\ParamUsers:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        my_provider:
            entity:
                class: GosylCommonBundle:ParamUsers
                property: username
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
           pattern: ^/login
           security: false

        main:
            pattern: ^/
            anonymous: true
            
            user_checker: app.user_checker
            
            form_login:
                login_path: login
                check_path: login_check
                
            provider: my_provider
            
            logout:
                path: logout
                target: /
                
            remember_me:
                secret: "%secret%"
                lifetime: 86400
                path: /
            
            http_basic: ~
    
    # Ne pas oublier d'insérer dans app/config/security.yml les ACL !!!